[package]
name = "scpl"
version = "0.2.0"
authors = ["leo-tom <ttnistomura@gmail.com>"]
license = "GPL-3.0-or-later"

[dependencies]
image = "*"
num = "*"
num-complex = "*"
num-traits = "*"
regex = "*"